services:
  posts-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
        
  posts:
    image: posts
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      WEBSITES_PORT: 5000
    build:
      context: ./Posts
      dockerfile: Posts.API/Dockerfile
    depends_on:
      - posts-database